/**
 * Sentry Performance Monitoring & Crash Reporting
 *
 * Initializes @sentry/react-native with Performance Tracing.
 * Only activates when a valid DSN is configured (staging/production).
 *
 * Usage:
 *   import { initSentry, captureException } from '@/lib/sentry';
 *
 *   initSentry();                    // call at app startup
 *   captureException(error);         // manually report errors
 */
import * as Sentry from '@sentry/react-native';
import { env } from '@/lib/env';
import { logger } from '@/lib/logger';

let initialized = false;

/**
 * React Navigation integration for automatic route tracing.
 * Created at module level so it can be exported and wired to NavigationContainer
 * via registerNavigationContainer() BEFORE Sentry.init() is called.
 *
 * In @sentry/react-native v8, the integration MUST observe navigation events
 * through the NavigationContainer ref to create transactions. Without this,
 * Performance/Tracing produces zero data.
 *
 * IMPORTANT: registerNavigationContainer() is called in App.tsx's useEffect,
 * NOT in navigationRef.ts at module level. This is because the Sentry
 * integration extracts navigationRef.current at call time — at module load
 * the ref's current is null (NavigationContainer hasn't mounted), so Sentry
 * silently drops all navigation listeners, producing zero Tracing data.
 * See App.tsx lines 162-167 for the registration call.
 *
 * @see {@link registerNavigationContainer} in App.tsx
 */
export const reactNavigationIntegration = Sentry.reactNavigationIntegration({
  routeChangeTimeoutMs: 500,
});

/**
 * Initialize Sentry SDK.
 * Safe to call multiple times — only runs once.
 */
export function initSentry(): void {
  if (initialized) {
    return;
  }

  // Never initialize Sentry in dev mode — Metro hot-reload + Sentry SDK debug
  // output causes significant noise and the staging DSN may be active even when
  // __DEV__ is true (e.g. Android staging flavor connected to Metro).
  if (__DEV__) {
    logger.info('[Sentry] Dev mode — Sentry disabled');
    return;
  }

  if (!env.SENTRY_DSN) {
    logger.info('[Sentry] DSN not configured — skipping initialization');
    return;
  }

  Sentry.init({
    dsn: env.SENTRY_DSN,
    enabled: env.SENTRY_ENABLED,
    environment: env.BUILD_VARIANT,
    release: `frontend-blog-mobile@${__DEV__ ? 'dev' : env.BUILD_VARIANT}`,

    // ── Performance Tracing ──────────────────────────────────────────
    // 100% in dev/test to catch issues early; 20% in production to reduce overhead.
    // WARNING: tracesSampleRate=1.0 in production caused a Sentry SDK infinite loop
    // (withScope → withSetScope → create_tSpan → emit) on HomeScreen due to
    // concurrent startInactiveSpan calls triggering recursive scope propagation.
    // Keep at 0.2 for production — still statistically significant for trend analysis.
    tracesSampleRate: env.SENTRY_ENABLED ? (__DEV__ ? 1.0 : 0.2) : 0,
    // Profile 20% of sampled transactions (reduced from 1.0 to match traces rate)
    profilesSampleRate: env.SENTRY_ENABLED ? (__DEV__ ? 1.0 : 0.2) : 0,

    // ── Sentry Logs ──────────────────────────────────────────────────
    // Enables logEnricherIntegration + consoleLoggingIntegration which
    // capture console.log/warn/error and send them to Sentry Logs.
    // Note: Requires a Sentry plan that includes the Logs product.
    enableLogs: true,

    // ── Session Replay ───────────────────────────────────────────────
    // Only enable for production with lower rate to save bandwidth
    replaysSessionSampleRate: env.SENTRY_ENABLED && !__DEV__ ? 0.1 : 0,
    replaysOnErrorSampleRate: env.SENTRY_ENABLED ? 1.0 : 0,

    // ── Integrations ─────────────────────────────────────────────
    integrations: [reactNavigationIntegration],

    // ── Breadcrumb filter ────────────────────────────────────────
    // Drop "Unable to find click target" breadcrumbs generated by Sentry's
    // Native touch tracker when the user taps a pure-native component
    // (e.g. react-native-video's <Video> → ExoPlayer/AVPlayer).
    // These are noise: Sentry detects the touch at the OS level but can't
    // resolve it to a React component, so no useful info is captured anyway.
    beforeBreadcrumb(breadcrumb) {
      if (breadcrumb.category === 'touch' && breadcrumb.message == null) {
        return null; // drop empty touch breadcrumbs
      }
      return breadcrumb;
    },

    debug: __DEV__ && !!env.SENTRY_DSN,
  });

  initialized = true;
  logger.info('[Sentry] Initialized', {
    environment: env.BUILD_VARIANT,
    tracesSampleRate: env.SENTRY_ENABLED ? (__DEV__ ? 1.0 : 0.2) : 0, // Keep sync with actual value above
  });
}

/**
 * Report an exception to Sentry with optional context.
 */
export function captureException(
  error: Error,
  context?: Record<string, unknown>,
): void {
  Sentry.captureException(error, {
    extra: context,
  });
}

/**
 * Record a breadcrumb for Sentry event trail.
 */
export function addBreadcrumb(
  message: string,
  category?: string,
  data?: Record<string, unknown>,
): void {
  Sentry.addBreadcrumb({
    message,
    category: category ?? 'app',
    data,
    level: 'info',
  });
}

export { Sentry };
